### ISSUE TITLE
Feature: Filter by furniture category

### ISSUE THREAD

**Issue by wookiefriseur** [manavortex/FurnitureCatalogue#39]
_Moved here from_ https://github.com/BerylBones/FurnitureCatalogue/issues/5

---

### Description
Add filters for furniture category/subcategory like `lightsource`, `interactable`.

### Thoughts
Would require UI changes to accomodate the new filters. If this clutters the UI too much just a checkbox for `interactable` might be enough for now (until some UI overhaul).

---

### ToDo

- [ ] check if list of categories and subcategories is correct
- [ ] check if category for furniture is identified correctly
- [ ] limit to relevant categories
- [ ] add filter to filter function
- [ ] create UI elements (icons or dropdown)

---

### Code
Some code snippets that might be useful for this feature. Only did a quick check, needs verification.

```lua
function getFurnitureCatFromChat(arg)
    if #arg > 0 then
        d(zo_strformat("Parameter: <<1>>", arg))

        local furnitureId = GetItemLinkFurnitureDataId(tostring(arg))
        d(zo_strformat("Fur ID: <<1>>", furnitureId))

        local furnitureInfo = GetFurnitureDataInfo(furnitureId)
        d(zo_strformat("cat <<1>>, subcat <<2>>", furnitureInfo))
        
        local categoryId
        local subcategoryId
        categoryId, subcategoryId = furnitureInfo
        local categoryName = GetFurnitureCategoryName(categoryId)
        local subcategoryName = GetFurnitureCategoryName(subcategoryId)
        d(zo_strformat("Fur Cats: <<1>>, <<2>>", categoryName, subcategoryName))
    end
end

function getAllFurCats()
    local cats = {}
    for i = 1, GetNumFurnitureCategories(), 1 do
        local iid = GetFurnitureCategoryId(i)
        local entry = {id=iid, name=GetFurnitureCategoryName(iid), subcats={}}
        table.insert(cats, entry)
        local subcatNum = GetNumFurnitureSubcategories(iid)
        if subcatNum > 0 then
            for j = 1, subcatNum, 1 do
                local jid = GetFurnitureSubcategoryId(iid, j)
                local subentry = {id=jid, name=GetFurnitureCategoryName(jid)}
                table.insert(cats[i].subcats, subentry)
            end
        end
    end

    return cats
end
```

**Comment by wookiefriseur** [comment]
Feedback from @Lyhtande ([Neverlands](https://www.esoui.com/forums/member.php?u=34006)):

>  Would it be possible to select multiple filters?

### My answer:
Right now multiple different filters can be combined, but not from the same drop down menu, if that's what you meant. I will look into multi select lists / combo lists. Wanted to do that when adding new filters

### TODO
- keep multi filter in mind, when extending the filter system

**Comment by wolfstar07** [comment]
I think after the database work and sourcing are complete, this would be the better direction to turn. It'll give more bang for our buck, though I agree we'll need to rework the UI for it.

**Comment by manavortex** [comment]
Don't forget to update the ESOUI screenshots 😏

**Comment by wolfstar07** [comment]
This is somewhat what I was thinking for furnishing categories. I don't remember if purchasable furnishings even get assigned craft stations since they're not crafted, so I'm not expecting to filter non-crafted items through it, but the category sub-filters would work whether you picked a craft station or a source filter.

<img width="1536" height="1024" alt="Image" src="https://github.com/user-attachments/assets/8ac6d1b9-77f5-4ff0-837e-04d0d71d2678" />

**Comment by wolfstar07** [comment]
A preview. Currently, the furnishing sub-categories sort the source filters and the crafting professions. I'll push the files later today before I try working on the source filters. I didn't want to change the existing layout too much from what users are used to.

<img width="1234" height="658" alt="Image" src="https://github.com/user-attachments/assets/2bd73e45-a4d9-4b8d-9c03-9fd820a48a7a" />

**Comment by wolfstar07** [comment]
New filters complete. Screenshots will be updated when we've finished the UI and DB changes.
