### ISSUE TITLE
Maintenance: Move Furniture Database into a Lib

### ISSUE THREAD

**Issue by wookiefriseur** [manavortex/FurnitureCatalogue#41]
_Moved here from_ https://github.com/BerylBones/FurnitureCatalogue/issues/16

---

### Description

Currently all furniture data is a fixed part of the main add on. It might be a good idea to move it into a separate library `LibFurniture`.

### Pros for splitting

**FAM** 🤡:

- **F**lexibility 
  - users who just want the tool tip but not the main add on could just use the library instead
  - most updates are database updates anyways, which could be made and tracked better in a separate library
- **A**vailability
  - makes it available for other add ons
  - can increase contributions to the database and the main add on
- **M**aintainability
  - a good API can remove duplicate code and improve code structure and readability
  - easier code changes in the future

---

Checklist / Thoughts: 
- [ ] add utility function or mini API for DB queries, so that the actual query has to be changed in only 1 spot
- [x] plan library implementation
  - [x] check if [LibCharacterKnowledge](https://www.esoui.com/downloads/info3317-LibCharacterKnowledge.html) is suitable
  - ~[ ] or look for other lib / ask authors for features~
  - ~[ ] or move current saved vars structure to own library~
- [ ] swap query method 
- [ ] clean saved vars and rescan knowledge if necessary
  - [x] check if there is any furniture data that has to be migrated / left in
  - [ ] make sure there is no loss of settings or other saved vars, only furniture knowledge
- [x] add lib requirement

**Comment by manavortex** [comment]
I was already gone before LCK hit, but from here, it looks like exactly the right kind of library for that purpose, and it'd let FurC drop the information from the saved variables (and skip the parsing).

## Pro: 
- smaller saved vars
- less logic inside FurC

## Cons: 
- Another dependency

## To investigate: 
- I'm assuming that since this thing is a library, the author will have optimized the shit out of performance (I tried my best back when, but I mostly focused on removing bottlenecks). I'd advise taking a good long look at whether or not FurC will still filter performantly when you chuck in the library, though :)

**Comment by wookiefriseur** [comment]
This one is actually 2 issues:

## 1: LCK for SavedVars

I'll do that for sure because of the mentioned pros. About performance: I think there was some addon that records loading times and other stats for addons. I'll try to use that, if there is no directly noticeable improvement.

## 2: Putting the FurnitureDB into its own Lib

Not sure yet about the separate library. It would  be easier to update, because we would not have to touch the main addon code for every luxury furnishing update and so on, but I have to check that first.

I can prepare the split and then just leave the lib inside the add on, without any cons. And then decide on a split later, if other authors ask for it.

**Comment by manavortex** [comment]
#1
I guess you could also find a volunteer with a potato PC and ask them to test a beta version. We all have someone like that in a guild we're in, don't we?

#2 
I actually considered that, but Users Are Lazy And Don't Read (Or Stupid And Can't Read, Not Sure Which). If you split out the furniture data, you'll end up drowning in bug reports "i CaN'T sEe ThIs WeEk's lUxUrY FuRnItUrE dAtA". That's why I decided against it, but you're of course free to reconsider. (If Minion can auto-update dependencies by now, the problem will have evaporated - can it?)

**Comment by wookiefriseur** [comment]
1: Oh, good idea. I can throttle my PC down to 🥔 levels.

2: Minion can update libs, but it does not yet automatically download missing libs. That feature is only available in Minion4 I think, which was not yet released.

**Comment by wookiefriseur** [comment]
Small update regarding DB changes (in case I die trying and someone else want's to pick up the torch) :

I'm thinking about testing different data structures and comparing performance to the current one. If it's worse, I will think of something else.  If it's better I will take that as the new base line. Rinse and repeat.

First try will be a naive SQL like structure, without trying to be smart with LUA, and seeing where that gets me:

```lua
FurC.DB['Items'] = { 
 [1234] = { ... } 
}
FurC.DB['Traders'] = { 
  [1] = { 
    name = "M'aiq",
    type = 2, -- reference to type like "Made Up Furnishing Vendor"
    location = "some location reference or string",
  },
  [123] = {
    name = "Heralda Somethingname",
    type = 6, -- reference to type like "Holiday Furnishing Vendor"
    location  = "reference to string like 'in all Capital Cities'",
  }
}
-- and so on

-- example for an item:
local mytem = {
  id = 1234, -- some item id
  src = 5, -- id of item source like CROWN, RUMOUR, LUXURY etc
  version = 3, -- Game Version reference
  price = 1234, -- price, currency type depends on src 
  sold_by =  { 1,2,3 } -- or something like that 
  some_other_optional_stuff = nil,
}
```

Should take less memory than the current way but might take longer to lookup, which is why I want to test it.
I used [ESO Profiler](https://www.esoui.com/downloads/info2166-ESOProfiler.html) to get a basic trace log (85MB). But now I cannot get it displayed in the trace viewer because it is unable to correctly convert the `.lua` to a `.json`. So right now I am trying to get a lua script running that converts a lua tracelog to a json tracelog. 🤷 If that fails I will fix the conversion plugin in the viewer or just do it in Python with regex. And only after all that will I be able to check performance. 😅

So right now:

- [x] get tracelog viewer working to measure performance
- [x] think of some useful DB structure
- ~~[ ] change DB~~
- [x] compare performance
- [x] ????
- ~~[ ] profit~~

-----
Edit

## Data Structure Ideas

### ToDo: check performance and size when using fixed hstructure instead of tables (just for the DB)

```lua
-- hstructure example
hstructure PERSON
  name: string
  age: number
end

function hstructThis()
  local p1 : PERSON = hmake PERSON { name = "Peter", age = 12}
  local p2 : PERSON = hmake PERSON { name = "Sarah", age = 34}
  local people = { p1, p2 }
  for index, value in ipairs(people) do
    d(zo_strformat("Name: <<1>> , Age: <<2>>", value.name, value.age))
  end
end
```

**Comment by wolfstar07** [comment]
I've surprise updated other addons with new libraries and haven't had any complaints. I just take care to list it in the change log and update the addon page, and thus far that seems to work. LCK would be great for all the crafted furnishings, and people using FC probably use other addons which require LCK anyway, so I don't think that will bother anyone. If we create a new library for all other furnishings (love that idea!), I don't think it will create a huge burden on users. As far as I've seen, FC is the only addon which also tracks furnishings from non-crafted sources. And then the only time FC would need updating is with each new game version, since I'm pretty sure code is on top of adding new blueprints.

**Comment by wookiefriseur** [comment]
Nice!

I was prototyping LCK before I stopped playing and it was working, I think. My plan was/is (also writing this as roadmap for myself) :

### LibCharacterKnowledge

Comment moved to #192 

### Split DataBase

Comment moved to #196 

### Updating Furniture info

Comment moved to #195 

### Overall

Not sure yet about the webinterface exactly yes. However together with the other stuff there is enough to split the work, if you like some. But I am already happy that you're keeping FC up to date. Let me know what you think of the ideas, whether they're ok or if I'm missnig something. Don't feel pressured to having to do something though, you're already helping.

>I just take care to list it in the change log and update the addon page, and thus far that seems to work.

Is the current version here up to date with the release version on esoui? I don't want to accidentally work on old stuff 😉
